adding hardware documentation #7
echopen/echopen_prototyping pull request #33
Opened 2017-05-11 13:54 UTC by jerome2echopen

2017-05-11 15:51 UTC, Aurelie-Mutschler commented
ping @Bivi could you please review the hardware documentation @jerome2echopen just made? we need some feedbacks, for example are there enough details or should we add some information ?

2017-05-11 17:13 UTC, Bivi commented
For me the second diagram is confusing : in french, very similar to the first one and false (we never decided to control directly the TGC with a smartphone ...). It would be simpler and more usefull to choose only one diagram (even if the first one is functional and the second a design diag) and add one paragraph for each component containing all data concerning this component and links with others, . Example :

     ...
## TGC
Time Gain Compensation, is an electronic component used to compensate signal attenuation during time.  TGC output is theoretically in range +/- 2.5 V, generally it is between +/- 1V....bla bla bla. TGC amplifies signal from ... TGC is controlled by ... TGC output is used by ...
### TGC caracteristic:
Amplification command: between 0 and 1 V
Amplification on LO gain mode: from -4.5 to +43.5 dB
Amplification on HI gain mode: from +7.5 to +55.5 dB
Output: between -2.5 and +2.5 V
### TGC Settings
TGC: LO gain mode (less amplification but too much noise on HI gain mode)
TGC amplication command: between 0.3 and 1 V (so amplification is between 10 and 43.5 dB)
   ...

2017-05-12 16:45 UTC, Aurelie-Mutschler commented
thanks @Bivi !
I wait for @jerome2echopen to update the file before I merge the PR. I'll have a look at it more in details by the beginning of next week.

2017-05-16 11:59 UTC, jerome2echopen commented
Yep, the synoptic diagram was wrong, I forgot to made all modifications needed.

I changed the order of the diagram with few description so one can look at one or the other. If you still think it is redundant, we will clear it.

I don't agree with the vision of describing all modules one by one like this. It is not the technical documentation of the hardware, it is a more general discussion about the device. And I think it preferable to put all the settings together so one don't have to navigate in the document to find all of them.

I make a new pull request.

2017-05-17 13:39 UTC, Aurelie-Mutschler requested changes
Here are some comments about the hardware documentation and the device characteristics.

2017-05-17 13:39 UTC, Aurelie-Mutschler commented on stable/characteristics.md
> +By default we use a 60° sector, 64 lines and measure from 80 to 160 mm depth. We these settings, we have 1689 points per lines. So an image is composed of 108096 points (the sector image can be inclu
I don't understand how we deduce the number of points per line from the previous sentence ?! The number of points is just related to the listening time and sampling rate, right? Why is the number of points constant for all depth values ? Does that mean that you change the sampling rate ?!

2017-05-17 13:39 UTC, Aurelie-Mutschler commented on stable/characteristics.md
> +The device is used as an access point and a terminal must connect to it. The device send the RAW data encoded on 16 bits *via* TCP protocol to the terminal (so an image has a size of 4.2 Mbits). The
The information about image size  is relevant here, but the description of the data transfer between device and terminal should be in doc_hardware.md

2017-05-17 13:39 UTC, Aurelie-Mutschler commented on stable/characteristics.md
> +For making an image, the terminale receive the data, for each line it determines the envelope of the signal with an Hilbert transform. When all the lines of an image are received and processed, the t
Similarly, this paragraph is a description of the functionning, not a characteristic, it shouldn't be here.
+ it's incomplete, the scan conversion isn't mentioned. Anyway, this should be in the software documentation, so just delete this paragraph please

2017-05-17 13:39 UTC, Aurelie-Mutschler commented on stable/characteristics.md
> +## Informations
This section should include the following pieces of information :
- recall the default tunings of the device --> There should be a **subsection "Default tunings"** where you recall these informations
- depth of detection, angular coverage --> the paragraph about depth of detection is not clear to me ? + these informations should be in a **subsection "Detection characteristics"**
- SNR --> can you quantify this + add the nice figures you made to visualize the last improvement? --> in a **subsection "Raw signal characteristics"**
- number of pixels, size of pixels, framerate --> can you gather those informations together with the image size, in a unique **subsection "Display characteristics"** ? 
- add a screenshot of a beautiful echOpen image :-)

2017-05-17 13:39 UTC, Aurelie-Mutschler commented on stable/doc_hardware.md
> +In this section we present a short documentation of our kit. More informations about the hardware can be found in our [website](http://echopen.org/doc-website/CAT-configuration/CFG-sweeping_probe/con
- The link to the documentation website points to the old configuration --> @Bivi when will the website be updated with the new configuration ?

- On the repo, the config "Aquarium" is v2.1.0, whereas it's supposed to be v3.0.0

2017-05-17 13:39 UTC, Aurelie-Mutschler commented on stable/doc_hardware.md
> +### Synoptic diagram
The synoptic diagram seems incomplete. For example, where is the high voltage ? And the WIFI ?

2017-05-17 13:39 UTC, Aurelie-Mutschler commented on stable/doc_hardware.md
> +### Block diagram
The bloc diagram is not up-to-date as it still shows the envelope detection, but it's not implemented on the device. 
Besides, I agree with @Bivi remark about the two diagrams. Let's get rid of this bloc diagram here, @clecoued and I will do a more general one that describes the device + app pipeline.
Then, the synoptic diagram should be more exhaustive (see first sentence in this comment)

2017-05-17 13:39 UTC, Aurelie-Mutschler commented on stable/doc_hardware.md
> +### Acoustic
Can you move the "### Acoustic" section to characteristics.md, in a dedicated "Transducer characteristics" section ?

2017-05-17 13:39 UTC, Aurelie-Mutschler commented on stable/doc_hardware.md
> +![](./doc_hardware/signalt.png "Temporal pulse of the transducer")
Can you at least put a legend to describe the content of the figures ?

2017-05-17 13:39 UTC, Aurelie-Mutschler commented on stable/doc_hardware.md
> +### Electronic (analogic)
Here you mix description and characteristics. Is it possible to keep only the description in doc_hardware.md and move the signal characteristics in characteristics.md?
Anyway, this section is not clear, it should be at least more structured

2017-05-17 13:39 UTC, Aurelie-Mutschler commented on stable/doc_hardware.md
> +Considering that the acoustic waves makes back and forth between the transducer and the medium, depth of measurement is given by d=v*t/2. So maximum depth of measurement at 125 Msps is **97 mm** and
The discussion about maximal depth should rather be in characteristics.md.
Besides, I don't understand at all the explanations given here. What's the link between sampling rate and depth of detection ?! Why do the value of the sampling rate influences the maximal depth ?!

2017-05-18 10:25 UTC, Aurelie-Mutschler commented on stable/doc_hardware.md
> +### Synoptic diagram
discussed with @jerome2echopen : let's make a diagram focused on modules. The functional diagrams (general diagrams + pipeline of data processing) will be displayed in the high-level documentation

2017-05-24 16:57 UTC, Aurelie-Mutschler commented on stable/doc_hardware.md
> +* Envelope detection: [MDL-envelope_detector_v1](https://github.com/echopen/PRJ-medtec_kit/blob/master/electronic/modules/hardware/MDL-envelope_detector/MDL-envelope_detector_v1/readme.md)
as discussed, let's remove the envelope detection module ;-)

2017-05-24 17:10 UTC, Aurelie-Mutschler commented
@jerome2echopen thanksss the doc_hardware.md is awesome !! ;-)
there's still a link to the envelope detection module that has to be dismissed. Otherwise I think we're good with doc_hardware.md
Waiting for updates of characteristics.md to merge the PR... to be continued !

2017-05-28 16:50 UTC, merged