#16 #65
echopen/echopen_prototyping pull request #73
Opened 2017-06-29 15:37 UTC by ApollineF

2017-07-02 13:00 UTC, Aurelie-Mutschler requested changes
Merci Apolline, j'ai mis quelques commentaires. Pourras-tu faire les petites modifs? J'attends pour accepter ta PR. Tu peux te contenter de faire les modifs sur ton fork, les commit seront automatiquement ajoutés dans cette PR

2017-07-02 13:00 UTC, Aurelie-Mutschler commented on challenges/challenges.md
> +A challenge is a problem encountered in the software development but that isn't related to a specific iteration. This means that anybody can suggest a solution at anytime ! One does not need to join
les challenges ne concernent pas forcément le software - il se trouve qu'actuellement on en a seulement pour le code de l'app mais il peut potentiellement y avoir des choses concernant le hardware ou traitement du signal par exemple. Pourras-tu modifier cela stp ?

2017-07-02 13:00 UTC, Aurelie-Mutschler commented on challenges/challenges.md
> +If you want to learn about one of those challenges, just click on the corresponding link and you will find everything you need: a description of the problem, code, ideas, so on and so forth. If have
bonne idée, mais dans ce cas il vaut mieux donner un point de contact ;)
je pense que tu peux mettre "contact us on slack" ou "by e-mail" (contact@echopen.org)

2017-07-02 13:00 UTC, Aurelie-Mutschler commented on inprogress/inprogress.md
> +As the fourth CapTech hasn't occured yet, the following subsections are empty:
top 👌

2017-07-11 12:51 UTC, Aurelie-Mutschler commented on SUMMARY.md
> +  * [About this GitBook](introduction/this_gitbook.md)
does this file exist?

2017-07-11 12:51 UTC, Aurelie-Mutschler commented on introduction/prototyping_gitbook.md
> +# Prototyping gitbook
this file won't show in the gitbook as it's not referenced in the summary.md
is that normal ?

2017-07-11 12:59 UTC, ApollineF commented on introduction/prototyping_gitbook.md
> +# Prototyping gitbook
Well, that's supposed to be the same document in fact, I just made a little mistake when I wrote the link. I've just corrected it.

2017-07-11 13:05 UTC, Aurelie-Mutschler approved these changes

2017-07-11 13:05 UTC, merged